# -*- coding: utf-8 -*-
"""Main_Project_EDA_Of_Waste_Management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9SF4sHJB3jzzIyuWinxSLY35HSVzqqp

*In case of any warnings or deprecations during code running, the following code has been put to avoid them.*
"""

import warnings
warnings.filterwarnings('ignore')

"""# **Pre-processing of Waste Management Data**

📊 Waste Management Data Analysis

This project focuses on analyzing a one-year trip summary dataset from a waste management company using the Python library pandas. The dataset includes information such as dates, customers, locations, waste types, drivers, activities, and sales personnel.

The main objective of this analysis is to explore the dataset, clean and preprocess the data, and extract meaningful insights. This includes identifying patterns in waste collection, understanding driver and customer activity, and analyzing operational efficiency.

The analysis will involve:

Data cleaning and preprocessing
Handling missing or inconsistent values
Converting data types for better performance
Performing exploratory data analysis (EDA)
Generating summary statistics and insights

By the end of this project, we aim to better understand the waste management operations and identify trends that can help improve decision-making and efficiency.

# Reading Data
Here, we import our dataset 'Trip rep 24.xlsx' from our Google Drive Link. As it is a .xslx file, we first convert it to a csv file for better data exploration. Importing Required Libraries (Data Processing)



- Pandas
- NumPy

These libraries are essential for data loading, cleaning, and preprocessing tasks.
"""

import pandas as pd
import numpy as np
df = pd.read_excel("https://docs.google.com/spreadsheets/d/1XwIxbzi465CuTdgra51CLkDP1jJki_2k/export?format=xlsx")

df.to_csv('data.csv', index=False)

"""# Handling Header Columns

Let us now take a look at our data's first few rows to examine it.
"""

df.head()

"""Now, I check the dataset size by finding how many rows and columns it contains."""

df.shape

""" As you can see, the header columns like 'Date', 'Month' etc. have been placed in the second row and not in the first. To fix this, let us first remove the first two empty rows."""

df = df.drop([0, 1]).reset_index(drop=True)
df.head()

"""Now, we must extract all the header column names from the 0th row."""

header_col_names = df.iloc[0].tolist()
header_col_names

"""Finally, we assign each column name to each column and rename them all."""

i = 0
for col in header_col_names:
  df = df.rename(columns = {
      f"Unnamed: {i}": col
  })
  i += 1
  if i >= len(header_col_names):
    break

df.head()

"""At last, we remove the 0th column as it unnecessary."""

df = df.iloc[1:]
df

"""# Handling Missing Values

Let us now take a look at some missing values in our dataset.
"""

df.isnull().sum()

"""Since both ID columns 'Tripsheet number' and 'Skip No' are not required for our data's visualization, we delete them to retain our data's integrity (and also since they contain a lot of Na values)"""

del df['Tripsheet number']
del df['Skip No']
del df['Manifest No']

"""Now, we gather all the numerical columsn and handle their missing values by replacing them with the respective column's mean."""

numerical_cols = df[['Quantity', 'Price', 'Amount', 'Vat 5%', 'Amount with Vat']]
for col in numerical_cols:
  df[col] = df[col].fillna(df[col].mean())

"""Let us now take a look at our other columns (string, object, etc.)"""

other_cols = df[[
    "Date",
    "Month",
    "Customer",
    "Location",
    "Waste Type",
    "Driver",
    "ACTIVITY",
    "Sales Person",
    "TRUCK NO"
]]

"""Here, we observe the 'Driver' column has a lot of missing values"""

other_cols.isnull().sum()

"""We are going to handle these missing values of 'Driver' column by replacing it with the mode Driver (most frequent)"""

df['Driver'] = df['Driver'].fillna(df['Driver'].mode()[0])

"""Let us now replace all the missing values of column 'TRUCK NO' by replacing them with 0"""

df['TRUCK NO'].fillna(0, inplace=True)

"""# Column Renaming

This step is used to standardize all column names in the dataset to make data analysis easier and error-free.
"""

df.columns = df.columns.str.lower().str.replace(" ", "_")
df.head()

"""In this step, i remove unwanted entries such as "rental" and "charges" from the waste_type column in the dataset. These values are not relevant for waste analysis and can affect the accuracy of insights."""

df = df[~df['waste_type'].str.lower().str.contains('rental|charges', na=False)]

"""Let us now take a look at our df's missing values."""

df.isnull().sum()

"""# DataType Assignment

Let us now change the datatypes of each column as to their needs.
"""

df.info()

"""First, let's convert the 'quantity' column to an int64, as it only holds integer values like 1, 2, etc."""

df.quantity = df.quantity.astype(int)
df['quantity'].head()

"""Now, let's convert the 'date' column to a datetype column."""

df.date = pd.to_datetime(df['date'])
df['date'].head()

"""Next, let's convert all potential categorical columns into category64 datatype.

All text-based columns in the dataset were converted to categorical type using astype('category')
"""

cat_cols = df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].astype('category')

df['truck_no'] = df['truck_no'].astype('category')

"""The truck_no column was converted to categorical type because it represents truck identifiers. This helps in better grouping and analysis of trips for each truck.

Finally, let us review our column's dataypes:
"""

df.info()

"""# Driver Column Cleaning"""

df.driver = df.driver.str.lower().str.strip()
df.driver

"""Fixing obvious invalid values"""

df['driver'] = df['driver'].replace(['N/a', 'n/a', 'N/A', 'NA'], 'No Name')

"""The driver column is standardized using regex replacement to unify different spellings of “Mohammed” (such as md, mohd, mohamad, muhammed) into a single consistent format. This improves data consistency for analysis.
Standardizing "Md / Mohd / Mohammed", as they represent the same person.   [Regex is a pattern-matching tool used to search, find, and replace text efficiently in a dataset.]
"""

df['driver'] = df['driver'].str.replace(r'\b(md|mohd|mohamad|muhammed)\b', 'mohammed', regex=True)

"""Let us fix some spacing issues in the 'driver' column.The driver column is cleaning by removing extra spaces and trimming leading/trailing whitespace. Multiple spaces were replaced with a single space to ensure consistent formatting of names."""

df['driver'] = df['driver'].str.replace(r'\s+', ' ', regex=True).str.strip()

"""As most of our names are different and complicated, we require a method of Manual Mapping, and assign each driver their respective, appropriate name."""

corrections = {
    'akthar': 'akhtar',
    'farook': 'farooq',
    'raouf': 'rauf',
    'dilnawaz': 'dil nawaz',
    'hasan': 'hassan',
    'umer': 'umar',
    'ali sah': 'ali shah',
    'mah ib': 'mohib',
    'fajan': 'fajad',
    'muqaraf': 'muqrab',
    'mugarab': 'muqrab',
    'muzalib': 'muzalif',
    'muzafid': 'muzalif',
    'zahed': 'zahid',
    'harris': 'haris',
    'sadik': 'sadiq'
}

df['driver'] = df['driver'].replace(corrections)

"""Now, let's return it back to its clean format.  I standardize the driver column by converting all names into title case to improve consistency and readability."""

df['driver'] = df['driver'].str.title()

df.driver.value_counts()

"""Finally, let's review our final, driver column.."""

print(list(df.driver.unique()))
print(df.driver.nunique())

"""During analysis, it was observed that some customers had multiple representations due to naming inconsistencies (e.g., "Nest Waste" and "Nest Waste(Noble)").

These variations were standardized into a single consistent name to avoid duplication and ensure accurate analysis of customer-wise waste generation.

This step improves data quality and ensures reliable insights in further analysis.
"""

df['customer'] = df['customer'].replace({
    'Nest Waste(Noble)': 'Nest Waste',
    'Nest Waste (Noble)': 'Nest Waste',
    'Nest Waste(Noble)': 'Nest Waste'
})

"""# **Exploratory Data Analysis**

QUANTITY COLUMN SEPARATION

The `quantity` column contains mixed information, where the value 1 represents a single trip, and values greater than 1 represent the weight of waste in kilograms.

To ensure accurate analysis, the data was separated into two categories: trip-based and weight-based entries.

This step splits the dataset into two separate groups based on the type of quantity. One dataset (trip_df) contains only the rows where the quantity type is “Trip”, and the other dataset (kg_df) contains only the rows where the quantity type is “KG”. This makes it easier to analyze trips and kilograms separately.

## Separate Analysis for Trips and Weight

After classifying the quantity values into trip-based and weight-based categories, separate analyses were performed for each dataset.

- `trip_df` was used to analyze trip frequency, operational workload, and service demand.
- `kg_df` was used to analyze waste quantity, waste types, and high-volume contributors.

This separation provided more meaningful insights and prevented incorrect interpretation of mixed quantity values.
"""

df['quantity_type'] = df['quantity'].apply(
    lambda x: 'trip' if x == 1 else 'kg'
)

trip_df = df[df['quantity_type'] == 'trip']
kg_df = df[df['quantity_type'] == 'kg']

df['quantity_type'].value_counts()

"""# **Analysis on trip_df (Trip-based)**"""

top_customers_trips = (
    trip_df['customer']
    .value_counts()
    .head(10)
)

top_customers_trips

trip_df['driver'].value_counts().head(10)

"""TRIPS OVER TIME    Busy months
Seasonal trends
"""

trip_df.groupby('month').size().sort_values(ascending=False)

trip_df.groupby('customer')['amount_with_vat'].sum().sort_values(ascending=False).head(10)

"""## **Analysis on kg_df (Weight-based)**

Who generates the most waste?  __    Largest waste contributors
"""

top_customers_kg = (
    kg_df.groupby('customer')['quantity']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_customers_kg

"""which drivers handling most waste?   """

kg_df.groupby('driver')['quantity'].sum().sort_values(ascending=False).head(10)

"""Most common waste categories"""

print("=== Trip-based Waste Types (by trip count) ===")
trip_waste_count = trip_df['waste_type'].value_counts().head(15)
print(trip_waste_count)

# KG-based waste type (already have this)
print("=== KG-based Waste Types ===")
kg_waste = kg_df.groupby('waste_type')['quantity'].sum().sort_values(ascending=False).head(10)
print(kg_waste)

"""# **Top Customers by Revenue**"""

top_kg_revenue = (
    kg_df.groupby('customer')['amount_with_vat']
    .sum()
    .sort_values(ascending=False)
    .head(10))
top_kg_revenue

top_trip_revenue = (
    trip_df.groupby('customer')['amount_with_vat']
    .sum()
    .sort_values(ascending=False)
    .head(10))
top_trip_revenue

"""# **Driver Trips vs Revenue**"""

driver_revenue = df.groupby('driver')['amount_with_vat'].sum()

driver_summary = pd.DataFrame({
    'trips': df['driver'].value_counts(),
    'revenue': driver_revenue
}).fillna(0)

driver_summary.sort_values('revenue', ascending=False).head(10)

"""# **VISUALIZATION**
Importing Visualization Libraries
After completing data preprocessing, and EDA .

These libraries help in understanding patterns, trends, and relationships in the dataset through graphical representation.


"""

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

"""# **Top Customers (Revenue)**"""

top_trip_customers = ( trip_df.groupby('customer', as_index=False)['amount_with_vat']
    .sum().sort_values(by='amount_with_vat', ascending=False) .head(10))

top_trip_customers['revenue_label'] = (top_trip_customers['amount_with_vat'].apply(lambda x: f'DHS {x:,.0f}'))

fig = px.bar(top_trip_customers,x='amount_with_vat',y='customer',orientation='h',
    text='revenue_label',title='Top 10 Customers by Trip Waste Revenue',color='amount_with_vat')

fig.update_layout( yaxis={'categoryorder':'total ascending'}, xaxis_title='Revenue (DHS)',
    yaxis_title='Customer')

fig.update_traces( textposition='outside', hovertemplate= '<b>%{y}</b><br>' + 'Revenue: DHS %{x:,.0f}<extra></extra>')

fig.show()

"""


 These top customers generate substantially higher amounts compared to the rest, showing that revenue is concentrated rather than evenly distributed across all customers. This suggests that maintaining strong relationships with these high-value clients is crucial for sustaining business stability and growth. At the same time, it also indicates a potential risk, as losing even a single major customer could significantly impact overall revenue. Therefore, while focusing on retaining and servicing these top customers efficiently, the business should also aim to diversify its customer base by attracting new clients to reduce dependency and ensure more balanced revenue distribution in the long term."""

top_kg_customers = (
    kg_df.groupby('customer', as_index=False)['amount_with_vat'] .sum()
    .sort_values(by='amount_with_vat', ascending=False).head(10))

top_kg_customers['revenue_label'] = (
    top_kg_customers['amount_with_vat']
    .apply(lambda x: f'DHS {x:,.0f}'))

fig = px.bar( top_kg_customers, x='amount_with_vat', y='customer',
    orientation='h', text='revenue_label',
    title='Top 10 Customers by KG Waste Revenue',
    color='amount_with_vat')

fig.update_layout( yaxis={'categoryorder':'total ascending'}, xaxis_title='Revenue (DHS)', yaxis_title='Customer')

fig.update_traces( textposition='outside', hovertemplate= '<b>%{y}</b><br>' + 'Revenue: DHS %{x:,.0f}<extra></extra>')

fig.show()

"""# **Monthly Revenue**

The monthly revenue analysis shows how business performance varies throughout the year in the UAE market. A clear drop in revenue is observed during Ramadan, which is a known low-performing period in the UAE due to reduced working hours, changes in business schedules, and overall slowdown in commercial activities across industries. Outside Ramadan, revenue remains more stable and increases during regular operational months when customer activity and trip demand are higher. This pattern is important for planning because seasonal and cultural factors in the UAE directly influence business flow. To improve performance, the company can prepare in advance for Ramadan by adjusting operations, optimizing schedules, and focusing on key customers to reduce revenue decline. At the same time, high-performing months can be used to maximize profit by strengthening customer relationships and improving service efficiency during peak demand periods.
"""

df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month_name()

monthly_revenue = df.groupby('month')['amount_with_vat'].sum()

months_order = [
    'January','February','March','April','May','June','July','August','September','October','November','December']

monthly_revenue = monthly_revenue.reindex(months_order)

plt.figure(figsize=(12,5))

bars = plt.bar(monthly_revenue.index,monthly_revenue.values)


for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2,bar.get_height(),
        f'{bar.get_height():,.0f}',ha='center', va='bottom')

plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""# **Sales Person Performance – Who Brought More Business?**

The sales person trend analysis compares the monthly revenue contribution of Shanir and Shameem to identify who brought more business over time. The results clearly show that Shanir generates higher revenue consistently across most months, making him the top contributor to overall business performance.To encourage and retain high performance from Shanir, the business can recognize his contribution through incentives, performance bonuses, or commission-based rewards, which will help maintain his motivation and loyalty.
"""

monthly_trend = df.groupby(['month','sales_person'])['amount_with_vat'].sum().unstack()

monthly_trend = monthly_trend.reindex(months_order)

plt.figure(figsize=(12,6))

for person in monthly_trend.columns:
    plt.plot(monthly_trend.index, monthly_trend[person], marker='o', label=person)

    for i, value in enumerate(monthly_trend[person]):
        if pd.notna(value):
            plt.text(i, value, f'{value:,.0f}', ha='center', va='bottom')


plt.title("Sales Person Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.legend(title="Sales Person")

plt.tight_layout()
plt.show()

"""# **Sales Person vs Customer Revenue Contribution Analysis**"""

heatmap_data = df.pivot_table(index='sales_person',columns='customer',values='amount_with_vat',
    aggfunc='sum',fill_value=0)

top_customers = df.groupby('customer')['amount_with_vat'].sum() \
                  .sort_values(ascending=False).head(10).index

heatmap_data = heatmap_data[top_customers]

plt.figure(figsize=(14,5))

sns.heatmap(heatmap_data,annot=True,fmt=".0f",cmap="Blues")

plt.title("Sales Person vs Customer Revenue Heatmap")
plt.xlabel("Customer")
plt.ylabel("Sales Person")

plt.tight_layout()
plt.show()

"""The heatmap shows the revenue contribution generated by each sales person across the top customers. Shanir stands out as the most active sales person, maintaining strong business relationships with a larger number of customers and contributing significantly to overall revenue. In contrast, other sales persons appear to handle fewer customer accounts or generate lower revenue levels. The analysis suggests that Shanir plays a key role in customer engagement and business generation within the organization

# **Customer Revenue Segmentation**
Classifying  ALL customers into tiers
"""

customer_revenue = df.groupby('customer')['amount_with_vat'].sum().reset_index()
customer_revenue.columns = ['customer', 'total_revenue']

customer_revenue['customer_tier'] = pd.cut(
    customer_revenue['total_revenue'],
    bins=[0, 5000, 20000, 50000, 999999],
    labels=['Small', 'Medium', 'Large', 'Premium'])

customer_revenue['customer_tier'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    title='Customer Revenue Segmentation')
plt.show()

"""# **KG vs Trip Revenue Analysis**  

The analysis shows that Trip-based work contributes 70.6% of the total revenue, while KG-based work contributes only 29.7%. This clearly indicates that the business is heavily dependent on Trip operations, which is the main source of income. KG work plays a secondary role but still adds a steady portion of revenue.
"""

kg_trip_revenue = df.groupby('quantity_type')['amount_with_vat'].sum()

plt.figure(figsize=(6,6))

plt.pie(
    kg_trip_revenue.values,
    labels=kg_trip_revenue.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops=dict(width=0.4)
)

plt.title("KG vs Trip Revenue Distribution")
plt.show()

"""## **Monthly Revenue + Trip Count**

"""

months_order = [
    'January','February','March','April','May','June',
    'July','August','September','October','November','December']

monthly_revenue = df.groupby('month')['amount_with_vat'].sum().reindex(months_order)

monthly_trips = df.groupby('month').size().reindex(months_order)

fig, ax1 = plt.subplots(figsize=(12,6))

ax1.plot(monthly_revenue.index, monthly_revenue.values, marker='o', color='blue')
ax1.set_ylabel("Revenue", color='blue')
ax1.set_xlabel("Month")

ax2 = ax1.twinx()
ax2.plot(monthly_trips.index, monthly_trips.values, marker='s', color='orange')
ax2.set_ylabel("Trip Count", color='orange')

plt.title("Monthly Revenue vs Trip Count (Activity vs Income)")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""Are more trips actually bringing more revenue?

The chart shows that revenue and trip count generally increase towards the end of the year, especially in the later months. This growth is not only due to higher operational activity but mainly because of increased customer reliability, stronger relationships, and continuous customer acquisition over time. As the business progresses through the year, more customers are added and existing customers place repeat orders, which leads to both higher trips and higher revenue.

Even though trip count increases steadily, revenue grows more strongly in the later months, showing that the business is not just handling more work but also improving in customer retention and trust-building.

# **Customer Repeat Analysis**
Which customers come back every month?
"""

customer_months = (
    df.groupby('customer')['month']
    .nunique()
    .reset_index())
customer_months.columns = ['customer', 'active_months']

customer_months['loyalty'] = pd.cut(
    customer_months['active_months'],
    bins=[0, 3, 6, 9, 12],
    labels=['One-time', 'Occasional', 'Regular', 'Loyal'])

customer_months['loyalty'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    title='Customer Loyalty Distribution'
)
plt.show()

"""The customer loyalty analysis reveals a concerning pattern — over half of all customers (54.9%) are one-time users who never returned for repeat service. Only 27.8% of customers fall into the Regular or Loyal categories, indicating that customer retention is a significant weakness in the current business model. This heavy dependence on one-time customers makes revenue unpredictable and increases the cost of customer acquisition. The company should urgently implement a customer retention strategy, including follow-up calls after first service, loyalty discounts for repeat customers, and dedicated account management for high-value clients, to convert one-time customers into long-term regulars.

# **Analysis of Driver Workload and Revenue Generation**
"""

plot_df = driver_summary.sort_values('revenue', ascending=False).head(10)

fig, ax1 = plt.subplots(figsize=(12,6))

ax1.bar(plot_df.index, plot_df['trips'])
ax1.set_ylabel('Number of Trips', color='blue')
ax1.set_xlabel('Driver')
ax1.tick_params(axis='y')

ax2 = ax1.twinx()
ax2.plot(plot_df.index, plot_df['revenue'], marker='o')
ax2.set_ylabel('Revenue (amount_with_vat)', color='green')

plt.title("Top 10 Drivers: Trips vs Revenue")
plt.xticks(rotation=45)
plt.show()

"""# **Driver Activity Classification**

Instead of just showing top 10 drivers, classify ALL 145 drivers into performance groups:
"""

driver_trips = trip_df['driver'].value_counts().reset_index()
driver_trips.columns = ['driver', 'trips']

driver_trips['performance'] = pd.cut(
    driver_trips['trips'],
    bins=[0, 20, 50, 100, 500],
    labels=['Inactive', 'Low', 'Moderate', 'Top Performer'])

driver_trips['performance'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    title='Driver Performance Distribution')
plt.show()

"""The driver performance analysis reveals that a small number of drivers contribute the majority of trips and revenue. Drivers such as Noor, Harjinder, and Gurpreet play a critical role in business operations, while several other drivers remain underutilized. The analysis also shows that higher trip counts do not always correspond to higher revenue, indicating differences in route value and customer importance. These findings highlight the need for better workload balancing and support the implementation of an ERP system for optimized driver allocation and operational efficiency.

# **Fleet Utilization Pattern: Driver–Truck Dependency Analysis**
"""

top_drivers = (
    df.groupby('driver')['amount_with_vat']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .index)
top_trucks = (
    df['truck_no']
    .value_counts()
    .head(10)
    .index)
filtered_df = df[
    (df['driver'].isin(top_drivers)) &
    (df['truck_no'].isin(top_trucks))].copy()

filtered_df['truck_no'] = filtered_df['truck_no'].astype(str)
heatmap_data = filtered_df.pivot_table(
    index='driver',
    columns='truck_no',
    values='customer',
    aggfunc='count',
    fill_value=0)

heatmap_long = heatmap_data.reset_index().melt(
    id_vars='driver',
    var_name='truck_no',
    value_name='trip_count')

fig = px.density_heatmap(
    heatmap_long,
    x='truck_no',
    y='driver',
    z='trip_count',
    color_continuous_scale='Blues',
    text_auto=True,
    title='Top Drivers vs Truck Utilization (Interactive)')

fig.update_layout(
    xaxis_title="Truck Number",
    yaxis_title="Driver",
    height=500)
fig.update_xaxes(type='category')

fig.show()

"""The heatmap shows that Noor is the top-performing driver with very high usage on Truck 75194, while Harjinder and Gurpreet mainly rely on Truck 64258, making it the most heavily used truck in the fleet. On the other hand, Sadham has very low activity across most trucks, showing underutilization. Overall, the pattern suggests drivers are mostly assigned to specific trucks rather than sharing them, which may indicate a need to improve fleet rotation and balance workload more evenly.

Customer Retention Analysis
Find customers who appeared in early months but disappeared later — these are churned customers worth investigating.

# **“Top 5 KG Waste Types — Monthly Quantity Trend”**
"""

top5_kg = ( kg_df.groupby('waste_type')['quantity'] .sum().sort_values(ascending=False) .head(5) .index)

months_order = ['January','February','March','April','May','June', 'July','August','September','October','November','December']

kg_filtered = kg_df[kg_df['waste_type'].isin(top5_kg)].copy()


kg_filtered['waste_type'] = pd.Categorical( kg_filtered['waste_type'], categories=top5_kg,   ordered=True)

kg_trend = ( kg_filtered.groupby(['month', 'waste_type'], observed=True)['quantity'] .sum() .reset_index())

kg_trend['month'] = pd.Categorical(kg_trend['month'],  categories=months_order,  ordered=True)

kg_trend = kg_trend.sort_values('month')

fig1 = px.line( kg_trend, x='month', y='quantity', color='waste_type',
    markers=True, title='Top 5 KG Waste Types — Monthly Trend',
    labels={'quantity': 'Total KG', 'month': 'Month'},
    category_orders={'waste_type': list(top5_kg)}  )
fig1.show()

"""The KG-based monthly trend reveals that Hazardous Waste is the single largest waste type by weight, peaking sharply in November and December, which may reflect industrial year-end compliance activity or large one-time collection jobs. The limited month coverage in KG data also indicates that weight-based collection is irregular and project-driven rather than consistent monthly operations, unlike trip-based waste which shows activity across all months

# **Monthly Trend Analysis of Top 5 Waste Types by Trip Frequency**
"""

top5_trip = (trip_df['waste_type'] .value_counts() .head(5) .index)

months_order = [
    'January','February','March','April','May','June','July','August','September','October','November','December']

trip_filtered = trip_df[trip_df['waste_type'].isin(top5_trip)].copy()

trip_filtered['waste_type'] = pd.Categorical(trip_filtered['waste_type'], categories=top5_trip, ordered=True)

trip_trend = (trip_filtered.groupby(['month', 'waste_type'], observed=True).size().reset_index(name='trip_count'))

trip_trend['month'] = pd.Categorical(trip_trend['month'],categories=months_order,ordered=True)
trip_trend = trip_trend.sort_values('month')

fig2 = px.line( trip_trend, x='month', y='trip_count',
    color='waste_type',markers=True,title='Top 5 Trip Waste Types — Monthly Trend',
    labels={'trip_count': 'Number of Trips', 'month': 'Month'},
    category_orders={'waste_type': list(top5_trip)})
fig2.show()

"""The monthly trip trend reveals that Concrete Waste is the most operationally demanding waste type, with a sharp peak in June suggesting construction-driven demand cycles. General Waste demonstrates consistent growth throughout the year, reflecting expanding customer activity. Wood Waste shows a seasonal uptick in the second half of the year, aligning with UAE’s cooler construction season. Foam and Food Waste remain minimal and consistent, contributing little to overall trip volume. These patterns suggest the business should increase truck and driver availability during June and October–December to handle peak demand efficiently.

# **Top 15 Waste Types by Total Quantity (KG) Distribution Analysis**
"""

kg_waste = ( kg_df.groupby('waste_type')['quantity'] .sum() .sort_values(ascending=False) .head(15)
    .reset_index())
kg_waste.columns = ['waste_type', 'quantity']

kg_waste = kg_waste[kg_waste['quantity'] > 0].copy()

fig = px.treemap(kg_waste, path=['waste_type'], values='quantity',
    title='Top 15 Waste Types by Quantity (KG) — Treemap')

fig.update_traces(textinfo='label+value+percent root')
fig.show()

"""# **Top 15 Waste Types by Trip Frequency Distribution Analysis**"""

trip_waste = ( trip_df['waste_type'] .value_counts().head(15).reset_index())
trip_waste.columns = ['waste_type', 'trip_count']


trip_waste = trip_waste[trip_waste['trip_count'] > 0].copy()

fig = px.treemap( trip_waste, path=['waste_type'], values='trip_count', title='Top 15 Waste Types by Trip Count — Treemap')

fig.update_traces(textinfo='label+value+percent root')
fig.show()

"""# **Conclusion**
The analysis showed that operations depend heavily on a few major customers, drivers, and trucks. Certain waste categories generated higher collection volumes, and monthly trends indicated changing operational demand.

# **Recommendations:**

* Balance driver workload efficiently
* Improve truck utilization and maintenance planning
* Focus on high-value customer retention
* Plan manpower and resources based on monthly demand
* Monitor major waste categories closely
* Improve data quality and reporting automation
* Consider implementing an ERP system for better operational **management**

# **Project Summary**
Analyzed waste management operational data using Python to identify trends in waste collection, customer activity, driver performance, and truck utilization.
"""